name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software for versions
        xcode:
          - 14.3.1
          - 15.2

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
